name: Feature request
description: Предложить новую возможность
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему решает функция?
      placeholder: Сейчас приходится вручную ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Как вы это видите?
      placeholder: Добавить переключатель в разделе ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      description: Другие способы, которые вы рассматривали.
